// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4GFfmav2Ygm0bG4usjtv5L1UOGQArB0',
    appId: '1:390742934912:web:c6481a88f3f047b7c26d65',
    messagingSenderId: '390742934912',
    projectId: 'exam-schedule-206024',
    authDomain: 'exam-schedule-206024.firebaseapp.com',
    storageBucket: 'exam-schedule-206024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6diCWIcdoGxh3WNB4H0JOZMjB84r10A',
    appId: '1:390742934912:android:cbff708b6ab409a4c26d65',
    messagingSenderId: '390742934912',
    projectId: 'exam-schedule-206024',
    storageBucket: 'exam-schedule-206024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1XLUSBOe4eVOIr7g0pNWzZM06CunKKDk',
    appId: '1:390742934912:ios:05c25354d1621d2ec26d65',
    messagingSenderId: '390742934912',
    projectId: 'exam-schedule-206024',
    storageBucket: 'exam-schedule-206024.appspot.com',
    iosBundleId: 'com.example.examSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1XLUSBOe4eVOIr7g0pNWzZM06CunKKDk',
    appId: '1:390742934912:ios:a941ac09843daba5c26d65',
    messagingSenderId: '390742934912',
    projectId: 'exam-schedule-206024',
    storageBucket: 'exam-schedule-206024.appspot.com',
    iosBundleId: 'com.example.examSchedule.RunnerTests',
  );
}
